version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: users
    ports:
      - '5432:5432'
