version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .env.local
    ports:
      - '5434:5432'
volumes:
  db:
    driver: local