version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=mostapchuk
      - POSTGRES_PASSWORD=MOstapcuk
    ports:
      - '5434:5434'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
