version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5433:5432'
volumes:
  db:
    driver: local
